// src/components/BackgroundShapes.tsx
import { motion } from "framer-motion";
import { useEffect, useState } from "react";

export function BackgroundShapes() {
  const [positions, setPositions] = useState<{ top: string; left: string }[]>([]);

  const generatePositions = () => Array.from({ length: 3 }).map(() => ({
    top: `${Math.floor(Math.random() * 70) + 10}%`, // 10% to 80%
    left: `${Math.floor(Math.random() * 70) + 10}%`, // 10% to 80%
  }));

  useEffect(() => {
    // Initial positions
    setPositions(generatePositions());

    // Update positions every 10 seconds for dynamic movement
    const intervalId = setInterval(() => {
      setPositions(generatePositions());
    }, 10000);

    return () => clearInterval(intervalId);
  }, []);

  const drawAnimation = {
    pathLength: [0, 1, 1, 0],
    pathOffset: [0, 0, 1, 1],
    opacity: [0, 1, 1, 0],
  };

  const transition = (duration: number, delay: number) => ({
    duration,
    delay,
    repeat: Infinity,
    ease: "easeInOut",
  });

  if (positions.length === 0) return null;

  return (
    <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
      {/* Circle - Info (Teal/Blue) */}
      <motion.svg
        width="100"
        height="100"
        viewBox="0 0 100 100"
        className="absolute blur-[1px]"
        animate={{
          top: positions[0].top,
          left: positions[0].left,
          y: [0, 20, 0],
          x: [0, 10, 0],
        }}
        transition={{
          top: { duration: 8, ease: "easeInOut" },
          left: { duration: 8, ease: "easeInOut" },
          y: { duration: 12, repeat: Infinity, ease: "easeInOut" },
          x: { duration: 12, repeat: Infinity, ease: "easeInOut" },
        }}
      >
        <motion.circle
          cx="50"
          cy="50"
          r="40"
          className="stroke-info fill-none"
          strokeWidth="2"
          strokeLinecap="round"
          animate={drawAnimation}
          transition={transition(8, 0)}
        />
      </motion.svg>

      {/* Rounded Square - Secondary (Pink/Purple) */}
      <motion.svg
        width="120"
        height="120"
        viewBox="0 0 120 120"
        className="absolute blur-[1px]"
        animate={{
          top: positions[1].top,
          left: positions[1].left,
          y: [0, -30, 0],
          rotate: [15, 25, 15],
        }}
        transition={{
          top: { duration: 9, ease: "easeInOut" },
          left: { duration: 9, ease: "easeInOut" },
          y: { duration: 15, repeat: Infinity, ease: "easeInOut" },
          rotate: { duration: 15, repeat: Infinity, ease: "easeInOut" },
        }}
      >
        <motion.rect
          x="10"
          y="10"
          width="100"
          height="100"
          rx="20"
          className="stroke-secondary fill-none"
          strokeWidth="2"
          strokeLinecap="round"
          animate={drawAnimation}
          transition={transition(10, 2)}
        />
      </motion.svg>

      {/* Triangle - Primary (Indigo/Purple) */}
      <motion.svg
        width="110"
        height="110"
        viewBox="0 0 110 110"
        className="absolute blur-[1px]"
        animate={{
          top: positions[2].top,
          left: positions[2].left,
          rotate: [-10, 10, -10],
          scale: [1, 1.05, 1],
        }}
        transition={{
          top: { duration: 10, ease: "easeInOut" },
          left: { duration: 10, ease: "easeInOut" },
          rotate: { duration: 18, repeat: Infinity, ease: "easeInOut" },
          scale: { duration: 18, repeat: Infinity, ease: "easeInOut" },
        }}
      >
        <motion.path
          d="M 55 10 L 100 95 L 10 95 Z"
          className="stroke-primary fill-none"
          strokeWidth="2"
          strokeLinecap="round"
          animate={drawAnimation}
          transition={transition(12, 4)}
        />
      </motion.svg>
    </div>
  );
}

// src/components/BackgroundShapes.svelte
<script lang="ts">
  let positions = $state<{ top: string; left: string }[]>([]);

  function generatePositions() {
    return Array.from({ length: 3 }, () => ({
      top: `${Math.floor(Math.random() * 70) + 10}%`,
      left: `${Math.floor(Math.random() * 70) + 10}%`,
    }));
  }

  $effect(() => {
    positions = generatePositions();
    const interval = setInterval(() => {
      positions = generatePositions();
    }, 10000);
    return () => clearInterval(interval);
  });
</script>

<div class="fixed inset-0 pointer-events-none overflow-hidden z-0">
  {#if positions.length > 0}
    <svg
      width="100" height="100" viewBox="0 0 100 100"
      class="shape1 absolute blur-[1px]"
      style="top: {positions[0]?.top}; left: {positions[0]?.left};"
    >
      <circle cx="50" cy="50" r="40" class="draw1 stroke-info fill-none" stroke-width="2" stroke-linecap="round" stroke-dasharray="251" />
    </svg>

    <svg
      width="120" height="120" viewBox="0 0 120 120"
      class="shape2 absolute blur-[1px]"
      style="top: {positions[1]?.top}; left: {positions[1]?.left};"
    >
      <rect x="10" y="10" width="100" height="100" rx="20" class="draw2 stroke-secondary fill-none" stroke-width="2" stroke-linecap="round" stroke-dasharray="366" />
    </svg>

    <svg
      width="110" height="110" viewBox="0 0 110 110"
      class="shape3 absolute blur-[1px]"
      style="top: {positions[2]?.top}; left: {positions[2]?.left};"
    >
      <path d="M 55 10 L 100 95 L 10 95 Z" class="draw3 stroke-primary fill-none" stroke-width="2" stroke-linecap="round" stroke-dasharray="250" />
    </svg>
  {/if}
</div>

<style>
  .shape1 { animation: shape1 12s ease-in-out infinite; }
  .shape2 { animation: shape2 15s ease-in-out infinite; }
  .shape3 { animation: shape3 18s ease-in-out infinite; }
  .draw1 { animation: draw1 8s ease-in-out infinite; }
  .draw2 { animation: draw2 10s ease-in-out 2s infinite; }
  .draw3 { animation: draw3 12s ease-in-out 4s infinite; }

  @keyframes shape1 {
    0%, 100% { transform: translateY(0) translateX(0); }
    50% { transform: translateY(20px) translateX(10px); }
  }
  @keyframes shape2 {
    0%, 100% { transform: translateY(0) rotate(15deg); }
    50% { transform: translateY(-30px) rotate(25deg); }
  }
  @keyframes shape3 {
    0%, 100% { transform: rotate(-10deg) scale(1); }
    50% { transform: rotate(10deg) scale(1.05); }
  }
  @keyframes draw1 {
    0%, 100% { stroke-dashoffset: 251; opacity: 0; }
    25%, 75% { stroke-dashoffset: 0; opacity: 1; }
  }
  @keyframes draw2 {
    0%, 100% { stroke-dashoffset: 366; opacity: 0; }
    25%, 75% { stroke-dashoffset: 0; opacity: 1; }
  }
  @keyframes draw3 {
    0%, 100% { stroke-dashoffset: 250; opacity: 0; }
    25%, 75% { stroke-dashoffset: 0; opacity: 1; }
  }
</style>
